#############################################################################
# Makefile for building: SudokuQT.app/Contents/MacOS/SudokuQT
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  SudokuQT.pro
# Template: app
# Command: /Users/Zaman/Applications/QT/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SudokuQT.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../Applications/QT/5.5/clang_64/lib/QtGui.framework/Headers -I../../Applications/QT/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Applications/QT/5.5/clang_64/mkspecs/macx-clang -F/Users/Zaman/Applications/QT/5.5/clang_64/lib
QMAKE         = /Users/Zaman/Applications/QT/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SudokuQT1.0.0
DISTDIR = /Users/Zaman/Desktop/SudokuQT/.tmp/SudokuQT1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Zaman/Applications/QT/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Zaman/Applications/QT/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sudoku_solver.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sudoku_solver.o \
		moc_mainwindow.o
DIST          = ../../Applications/QT/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/qdevice.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/unix.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/mac.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/macx.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/clang.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/qconfig.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/qt.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/resources.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/moc.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/uic.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/lex.prf \
		SudokuQT.pro mainwindow.h \
		sudoku_solver.h main.cpp \
		mainwindow.cpp \
		sudoku_solver.cpp
QMAKE_TARGET  = SudokuQT
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SudokuQT.app/Contents/MacOS/SudokuQT

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d SudokuQT.app/Contents/MacOS/ || mkdir -p SudokuQT.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SudokuQT.pro ../../Applications/QT/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../Applications/QT/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/qdevice.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/unix.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/mac.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/macx.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/clang.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/qconfig.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Applications/QT/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/qt.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/resources.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/moc.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/uic.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Applications/QT/5.5/clang_64/mkspecs/features/lex.prf \
		SudokuQT.pro \
		/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SudokuQT.pro
../../Applications/QT/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../Applications/QT/5.5/clang_64/mkspecs/qdevice.pri:
../../Applications/QT/5.5/clang_64/mkspecs/features/device_config.prf:
../../Applications/QT/5.5/clang_64/mkspecs/common/unix.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/mac.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/macx.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/sanitize.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/clang.conf:
../../Applications/QT/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../Applications/QT/5.5/clang_64/mkspecs/qconfig.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Applications/QT/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Applications/QT/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/qt_config.prf:
../../Applications/QT/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../Applications/QT/5.5/clang_64/mkspecs/features/spec_post.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/default_pre.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/default_post.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/warn_on.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/qt.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/resources.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/moc.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/uic.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/exceptions.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/yacc.prf:
../../Applications/QT/5.5/clang_64/mkspecs/features/lex.prf:
SudokuQT.pro:
/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SudokuQT.pro

qmake_all: FORCE

SudokuQT.app/Contents/PkgInfo: 
	@test -d SudokuQT.app/Contents || mkdir -p SudokuQT.app/Contents
	@$(DEL_FILE) SudokuQT.app/Contents/PkgInfo
	@echo "APPL????" > SudokuQT.app/Contents/PkgInfo
SudokuQT.app/Contents/Resources/empty.lproj: 
	@test -d SudokuQT.app/Contents/Resources || mkdir -p SudokuQT.app/Contents/Resources
	@touch SudokuQT.app/Contents/Resources/empty.lproj
	
SudokuQT.app/Contents/Info.plist: 
	@test -d SudokuQT.app/Contents || mkdir -p SudokuQT.app/Contents
	@$(DEL_FILE) SudokuQT.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,ZamanCorp.SudokuQT,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,SudokuQT,g" -e "s,@TYPEINFO@,????,g" ../../Applications/QT/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >SudokuQT.app/Contents/Info.plist

all: Makefile \
		SudokuQT.app/Contents/PkgInfo \
		SudokuQT.app/Contents/Resources/empty.lproj \
		SudokuQT.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h sudoku_solver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp sudoku_solver.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r SudokuQT.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		sudoku_solver.h \
		mainwindow.h
	/Users/Zaman/Applications/QT/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Zaman/Applications/QT/5.5/clang_64/mkspecs/macx-clang -I/Users/Zaman/Desktop/SudokuQT -I/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/Zaman/Applications/QT/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/Zaman/Applications/QT/5.5/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/Zaman/Applications/QT/5.5/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		sudoku_solver.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/QT/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		sudoku_solver.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sudoku_solver.o: sudoku_solver.cpp sudoku_solver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sudoku_solver.o sudoku_solver.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

